### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by geoffviola** [ros-gbp/roscpp_core-release#1]
Would it be possible for another release to be issued? I have a project downstream that could use changes from the roscpp_serialization particularly for the ARM release.

**Comment by dirk-thomas** [comment]
May I ask which patch to `roscpp_serialization` you are referring to and for which ROS distribution.

**Comment by geoffviola** [comment]
https://github.com/ros/roscpp_core/commit/ddd56f49341bb3a0aaf5dc368f8208920dccc81b on Kinetic

**Comment by dirk-thomas** [comment]
Making a new release just to address a compiler warning on ARM is a significant overhead.

In a couple of weeks the ROS core packages will likely get released due to other accumulated changes. I think this can wait until then. Sorry.
